[package]
name = "tapid-store"
readme = "README.md"
description = "Local content-addressed package store foundations for Tapid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tapid-archive = { version = "0.0.1", path = "../tapid-archive" }
tapid-core = { version = "0.0.1", path = "../tapid-core" }
sha2 = "0.10"
hex = "0.4"
