[package]
name = "tapid-linker"
readme = "README.md"
description = "Deterministic dependency materialization planning for Tapid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
tapid-core = { version = "0.0.1", path = "../tapid-core" }
