[package]
name = "tapid-linker"
readme = "README.md"
description = "Deterministic node_modules layout planning for Tapid"
version = "0.0.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
tapid-core = { version = "0.0.2", path = "../tapid-core" }
tapid-manifest = { version = "0.0.3", path = "../tapid-manifest" }
