[package]
name = "tapid-manifest"
readme = "README.md"
description = "Manifest parsing and package metadata models for Tapid"
version = "0.0.3"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tapid-core = { version = "0.0.2", path = "../tapid-core" }

[lib]
path = "src/lib.rs"
