[package]
name = "tapid-lockfile"
readme = "README.md"
description = "Deterministic lockfile models and serialization for Tapid"
version = "0.0.6"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tapid-core = { version = "0.0.4", path = "../tapid-core" }
url = "2"

[lib]
path = "src/lib.rs"
