[package]
name = "tapid-signatures"
readme = "README.md"
description = "Signing and verification foundations for Tapid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"
