[package]
name = "tapid-runner"
readme = "README.md"
description = "Policy-aware package execution foundations for Tapid"
version = "0.0.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
sha2 = "0.10"
tapid-policy = { version = "0.0.1", path = "../tapid-policy" }

[lib]
path = "src/lib.rs"
